config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  match '/', to: 'home#index', via: [:get, :post]
  resources :devices, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord

	belongs_to :tester
	belongs_to :device
	validates :tester, :device, presence: true
  
end

app/models/device.rb
class Device < ApplicationRecord

	has_many :bugs

	validates :description, length: { maximum: 255 }, presence: true

	def self.all_devices
		all.order(description: :asc).map{|e|[e.description, e.id]}
	end

	def self.all_with_bug_count
		select('devices.*, count(bugs.id) as bug_count').
			group('devices.id').
			left_joins(:bugs).
			order('devices.description')
	end
	
end

app/models/tester.rb
class Tester < ApplicationRecord

	has_many :tester_devices
	has_many :devices, through: :tester_devices
	has_many :bugs

	validates :first_name, length: { maximum: 60 }, presence: true
	validates :last_name, length: { maximum: 60 }, presence: true
	validates :country, length: { is: 2 }, presence: true

	def self.all_countries
		select(:country).order(:country).distinct.map(&:country)
	end

	def self.search(country=:all, devices=:all)
		query = select('testers.*, count(bugs.id) as bug_count').
			group('testers.id').
			left_joins(:bugs).
			order('bug_count desc')
		query = query.where(country: country) if !country.blank? and country != :all
		query = query.where(bugs: { device_id: devices }) if !devices.blank? and devices != :all
		query
	end

end

app/models/tester_device.rb
class TesterDevice < ApplicationRecord

	belongs_to :tester
	belongs_to :device
	validates :tester, :device, presence: true
	validates_uniqueness_of :device_id, :scope => :tester_id
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

	def index
		@devices = Device.all_with_bug_count
	end

	def show
		@device = Device.find(params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@countries = ['All'] + Tester.all_countries
		@devices = [['All', 'All']] + Device.all_devices
		@testers = search_for_testers
	end

	private

	def search_for_testers
		testers = []
		if params[:search]
			country = params[:search][:country]
			devices = params[:search][:devices]
			country = :all if country == "All"
			devices = :all if devices == ["All"]
			testers = Tester.search(country, devices)
		end
		testers
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def full_name(entity)
		"#{entity.first_name} #{entity.last_name}"
	end
	
end

app/views/devices/index.html.erb
<h2>Devices</h2>
<div class="row">
	<div class="col-md-12">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Id</th>
					<th>Description</th>
					<th>Bug Count</th>
				</tr>
			</thead>
			<tbody>
				<% @devices.each do |device| %>
				<tr>
					<td><%= device.id %></td>
					<td><%= link_to device.description, device_path(device) %></td>
					<td><%= device.bug_count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/devices/show.html.erb
<h2>Device - <%= @device.id %> - <%= @device.description %></h2>
<h3>Bugs</h3>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Id</th>
			<th>Tester</th>
		</tr>
	</thead>
	<tbody>
		<% @device.bugs.each do |bug| %>
		<tr>
			<td><%= bug.id %></td>
			<td><%= full_name bug.tester %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/home/index.html.erb
<% content_for :javascript do %>
<script type="text/javascript" >
	function update_devices() {
		var device_ids = $("#search_devices").val();
  	if (device_ids.length == 0) {
  		$("#search_devices").val('All');
  	} else {
  		if ($("#search_devices option[value=All]:selected").length > 0) {
				$("#search_devices").val('All');
			}
  	}
	}
  $(document).ready(function() {
  	update_devices();
  	$("#search_devices").change(function(){
  		update_devices();
  	});
  });
</script>
<% end %>

<h2>Search</h2>
<div class="row">
	<div class="col-md-4">
		<%= form_tag root_path do %>
			<%= label_tag 'search[country]', 'Country' %>
			<%= select_tag 'search[country]', options_for_select(@countries, selected: params.dig(:search, :country)), class: 'form-control mb-2'%>
			<%= label_tag 'search[devices]', 'Devices' %>
      <%= select_tag 'search[devices]', options_for_select(@devices, selected: params.dig(:search, :devices)), multiple: true, size: 12, class: 'form-control mb-2' %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
		<% end %>
	</div>
	<div class="col-md-8">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Name</th>
					<th>Country</th>
					<th>Bug Count</th>
				</tr>
			</thead>
			<tbody>
				<% @testers.each do |tester| %>
				<tr>
					<td><%= full_name tester %></td>
					<td><%= tester.country %></td>
					<td><%= tester.bug_count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bug Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to 'Bug Tracker', root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Devices', devices_path, class: 'nav-link' %>
            </li>
          </ul>
         
        </div>
      </div><!-- container -->
    </nav>
    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>